# Generated by Django 4.0.5 on 2022-06-06 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arte',
            name='idprod',
            field=models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Idproducto'),
        ),
        migrations.AlterField(
            model_name='arte',
            name='nombre',
            field=models.CharField(max_length=20, verbose_name='Nombre del arte'),
        ),
        migrations.AlterField(
            model_name='arte',
            name='precio',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombreCategoria',
            field=models.CharField(max_length=50, verbose_name='Nombre de la cetgoria'),
        ),
    ]
